### ISSUE TITLE
MCI OneBlock & SkyBlock Release Progress 1.17

### ISSUE THREAD

**Issue by SpikeyHelmet** [MCIndiaNetwork/MCI-Server#4]
We shall keep updating this thing from time to time as our progress goes ahead! Stay tuned! Most recent updates will be posted as comments after this issue!

### Our todo list:
- [x] Spawn Build Finalisation
   - [x] World Setup
   - [x] Mines
   - [x] Boost pads
   - [x] Special places
- [x] Ranks for a progression system.
- [x] Do agressive testing to check for gamebreaking bugs which might require a world reset
- [x] Open server up in beta (Progress can reset any day untill things are stable)
- [x] Release MCI OneBlock and SkyBlock Season 3 with the Caves and Cliffs update Part 1

### Important note:

This issue is to share our progress report with our public community so that people are not asking in game chat about SkyBlock and OneBlock. Yes we are working on it. 😄 

### Some important points about how SkyBlock and OneBlock will operate:
- The servers will be split into their own individual gameplay and they will not share inventories, money and ranks.
- We do not want to release with a broken gameplay experience so we would fix things before we release.

ETA for release of OneBlock & SkyBlock would be 18th November 2021.

**Comment by Itztasty** [comment]
:+1:

**Comment by kpisdapro** [comment]
Naiz gg pog mument xD

**Comment by rockojsj** [comment]
Do it !!!! Fast

**Comment by Ravi7302** [comment]
hii

**Comment by SpikeyHelmet** [comment]
We've planned for an 18th November 2021 Release.
More info will be posted as we get closer to release.

**Comment by SpikeyHelmet** [comment]
We've planned to release OneBlock and SkyBlock in 2 Phases.

## Phase 1 ✅

- New Rankup System which requires ingame currency and MCI Coins.
- MCI Coins added into the game.
- Extended Phases
- Fly
- PvP Arena
- New and revamped Spawn
- Revamped GUI Menus
and many more minor additions.

## Phase 2 🪄

- 2 New XPFarms
- Mines
- Custom Items
- Crates

OneBlock Phase 1 will release on 21st Nov at 10AM.
Release dates and update logs will be posted in this issue page.

# 🕹️ Stay Tuned
